name: install-yq
description: Install yq

runs:
  using: composite
  steps:
    - run: wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      shell: bash