name: bigbang-version-check

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  bb-version-compare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64'
          name: 'yq'
          version: 'latest'

      - name: Check bigbang version
        run: |
          chmod +x ./test/scripts/bb-compare.sh
          ./test/scripts/bb-compare.sh
